name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:

- name: free disk space
      run: sudo swapoff -a
      run:   sudo rm -f /swapfile
      run:  sudo apt clean
      run:  docker rmi $(docker image ls -aq)
      run:  df -h
