name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:

- name: free disk space
      run:
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
